name: CI push to ECR Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPO }}:latest .
          
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest